"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.contract = exports.web3 = void 0;
require('dotenv').config();
var Web3 = require('web3').Web3;
var web3 = new Web3(process.env.API_ADDRESS);
exports.web3 = web3;
var cAbi = process.env.CONTRACT_ABI;
var contractAbi = JSON.parse(cAbi);
var contract = new web3.eth.Contract(contractAbi, process.env.CONTRACT_ADDRESS);
exports.contract = contract;
